server:
  port: 8082

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.clb.domain
  mapper-locations: classpath:mapper/*.xml
  global-config:
    banner: off

spring:
  devtools:
    restart:
      additional-exclude: com/clb/util/Advice.class
      enabled: false

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_design?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    #    host: 192.168.0.88
    host: centos
    password: 123456
    port: 6379
    database: 0

feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        readTimeout: 10000
        connectTimeout: 10000

ribbon:
  okhttp:
    enabled: true

# 日志
logging:
  level:
    com.clb: debug
    root: info
  pattern:
    dateformat: "yy/MM-dd HH:mm:ss.SSS"