server:
  port: 10086


spring:
  cloud:
    gateway:
      # 路由配置
      routes:
        - id: reader_route
          uri: lb://ms-reader
          predicates:
            - Path=/reader/**

        - id: book_route
          uri: lb://ms-book
          predicates:
            - Path=/book/**

        - id: borrow_route
          uri: lb://ms-borrow
          predicates:
            - Path=/borrow/**

        - id: admin_route
          uri: lb://ms-admin
          predicates:
            - Path=/admin/**
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*" # 允许哪些网站的跨域请求
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
  #    sentinel:
  #      transport:
  #        dashboard: localhost:8079 # sentinel控制台地址


  redis:
    host: centos
    password: 123456
    port: 6379
    database: 0

  # 热重载
  devtools:
    restart:
      enabled: false



# 日志
logging:
  level:
    com.clb: debug
    root: info
  pattern:
    dateformat: "yy/MM-dd HH:mm:ss.SSS"

