server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_design?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  cloud:
    # nacos
    nacos:
      server-addr: localhost:8848
  application:
    name: book-service
logging:
  level:
    io.github.tankingcao: debug